services:
  - type: web
    name: rescript-scraper
    env: docker
    region: oregon
    plan: free
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: DISPLAY
        value: ":99"
      - key: CHROME_BIN
        value: "/usr/bin/google-chrome"
      - key: CHROMEDRIVER_PATH
        value: "/usr/local/bin/chromedriver"
