services:
  - type: web
    name: rescript-scraper
    env: python
    buildCommand: |
      chmod +x render-build.sh
      ./render-build.sh
    startCommand: |
      # Set up environment variables
      export DISPLAY=:99
      export PATH=$PATH:/opt/render/project/src/.local/bin
      export CHROME_BIN=/opt/render/project/src/.local/chrome/opt/google/chrome/chrome
      export CHROMEDRIVER_PATH=/opt/render/project/src/.local/bin/chromedriver

      # Start Xvfb
      Xvfb :99 -screen 0 1024x768x16 &

      # Start the application
      ./start.sh
    region: oregon
    plan: free
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: DISPLAY
        value: ":99"
      - key: CHROME_BIN
        value: "/opt/render/project/src/.local/chrome/opt/google/chrome/chrome"
      - key: CHROMEDRIVER_PATH
        value: "/opt/render/project/src/.local/bin/chromedriver"
